name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.HUB_ACCESS_TOKEN }}
    - name: Build the image
      run: docker build . --file Dockerfile --tag vlkuzmichev/my-django-pg-docker:latest
    - name: Push to Docker Hub
      run: docker push ${{secrets.DOCKER_HUB_USERNAME}}/my-django-pg-docker